// ============================================================
// Seed data — pre-populated menu items for the canteen
// ============================================================

import { MenuItem } from '@/types';

export const seedMenuItems: MenuItem[] = [
  // ---- SNACKS ----
  {
    id: 'snack-001',
    name: 'Samosa',
    description: 'Crispy golden pastry filled with spiced potatoes and peas. Served with mint chutney.',
    price: 20,
    category: 'snacks',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&h=300&fit=crop',
    isVeg: true,
    isAvailable: true,
    preparationTime: 5,
  },
  {
    id: 'snack-002',
    name: 'Vada Pav',
    description: 'Mumbai-style spiced potato fritter in a soft bun with chutneys.',
    price: 25,
    category: 'snacks',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880049?w=400&h=300&fit=crop',
    isVeg: true,
    isAvailable: true,
    preparationTime: 5,
  },
  {
    id: 'snack-003',
    name: 'Paneer Puff',
    description: 'Flaky puff pastry stuffed with spiced paneer and vegetables.',
    price: 30,
    category: 'snacks',
    image: 'https://images.unsplash.com/photo-1625220194771-7ebdea0b70b9?w=400&h=300&fit=crop',
    isVeg: true,
    isAvailable: true,
    preparationTime: 5,
  },
  {
    id: 'snack-004',
    name: 'Chicken Roll',
    description: 'Tender chicken wrapped in a warm paratha with onions and sauces.',
    price: 60,
    category: 'snacks',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&h=300&fit=crop',
    isVeg: false,
    isAvailable: true,
    preparationTime: 10,
  },
  {
    id: 'snack-005',
    name: 'French Fries',
    description: 'Crispy golden fries seasoned with herbs and spices. Served with ketchup.',
    price: 50,
    category: 'snacks',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&h=300&fit=crop',
    isVeg: true,
    isAvailable: true,
    preparationTime: 8,
  },
  {
    id: 'snack-006',
    name: 'Spring Roll',
    description: 'Crunchy vegetable spring rolls with sweet chili dipping sauce.',
    price: 40,
    category: 'snacks',
    image: 'https://images.unsplash.com/photo-1548507200-68a671a19b53?w=400&h=300&fit=crop',
    isVeg: true,
    isAvailable: true,
    preparationTime: 7,
  },

  // ---- BEVERAGES ----
  {
    id: 'bev-001',
    name: 'Masala Chai',
    description: 'Aromatic Indian tea brewed with ginger, cardamom, and fresh milk.',
    price: 15,
    category: 'beverages',
    image: 'https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?w=400&h=300&fit=crop',
    isVeg: true,
    isAvailable: true,
    preparationTime: 3,
  },
  {
    id: 'bev-002',
    name: 'Cold Coffee',
    description: 'Rich and creamy blended cold coffee topped with whipped cream.',
    price: 50,
    category: 'beverages',
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&h=300&fit=crop',
    isVeg: true,
    isAvailable: true,
    preparationTime: 5,
  },
  {
    id: 'bev-003',
    name: 'Fresh Lime Soda',
    description: 'Refreshing lime juice with soda, mint, and a hint of black salt.',
    price: 30,
    category: 'beverages',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=400&h=300&fit=crop',
    isVeg: true,
    isAvailable: true,
    preparationTime: 3,
  },
  {
    id: 'bev-004',
    name: 'Mango Lassi',
    description: 'Thick and creamy yogurt smoothie blended with ripe Alphonso mangoes.',
    price: 45,
    category: 'beverages',
    image: 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?w=400&h=300&fit=crop',
    isVeg: true,
    isAvailable: true,
    preparationTime: 4,
  },
  {
    id: 'bev-005',
    name: 'Buttermilk',
    description: 'Cool, spiced buttermilk with cumin and curry leaves.',
    price: 20,
    category: 'beverages',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400&h=300&fit=crop',
    isVeg: true,
    isAvailable: true,
    preparationTime: 2,
  },

  // ---- MEALS ----
  {
    id: 'meal-001',
    name: 'Veg Thali',
    description: 'Complete meal with dal, sabzi, rice, roti, salad, and pickle.',
    price: 90,
    category: 'meals',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop',
    isVeg: true,
    isAvailable: true,
    preparationTime: 15,
  },
  {
    id: 'meal-002',
    name: 'Chicken Biryani',
    description: 'Fragrant basmati rice layered with tender spiced chicken and saffron.',
    price: 120,
    category: 'meals',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&h=300&fit=crop',
    isVeg: false,
    isAvailable: true,
    preparationTime: 20,
  },
  {
    id: 'meal-003',
    name: 'Paneer Butter Masala + Naan',
    description: 'Rich and creamy paneer curry served with soft butter naan.',
    price: 110,
    category: 'meals',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&h=300&fit=crop',
    isVeg: true,
    isAvailable: true,
    preparationTime: 15,
  },
  {
    id: 'meal-004',
    name: 'Egg Fried Rice',
    description: 'Wok-tossed rice with eggs, vegetables, and Indo-Chinese seasonings.',
    price: 70,
    category: 'meals',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400&h=300&fit=crop',
    isVeg: false,
    isAvailable: true,
    preparationTime: 12,
  },
  {
    id: 'meal-005',
    name: 'Chole Bhature',
    description: 'Spicy chickpea curry with fluffy deep-fried bread.',
    price: 80,
    category: 'meals',
    image: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?w=400&h=300&fit=crop',
    isVeg: true,
    isAvailable: true,
    preparationTime: 12,
  },
  {
    id: 'meal-006',
    name: 'Rajma Chawal',
    description: 'Hearty kidney bean curry served with steamed basmati rice.',
    price: 75,
    category: 'meals',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop',
    isVeg: true,
    isAvailable: true,
    preparationTime: 15,
  },

  // ---- DESSERTS ----
  {
    id: 'des-001',
    name: 'Gulab Jamun',
    description: 'Soft milk-solid dumplings soaked in rose-flavored sugar syrup. (2 pcs)',
    price: 30,
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1666190050091-63f1726d1931?w=400&h=300&fit=crop',
    isVeg: true,
    isAvailable: true,
    preparationTime: 3,
  },
  {
    id: 'des-002',
    name: 'Chocolate Brownie',
    description: 'Warm, fudgy brownie with a molten chocolate center.',
    price: 50,
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400&h=300&fit=crop',
    isVeg: true,
    isAvailable: true,
    preparationTime: 5,
  },
  {
    id: 'des-003',
    name: 'Ice Cream Sundae',
    description: 'Vanilla ice cream with chocolate sauce, nuts, and a cherry on top.',
    price: 60,
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&h=300&fit=crop',
    isVeg: true,
    isAvailable: true,
    preparationTime: 4,
  },
  {
    id: 'des-004',
    name: 'Rasgulla',
    description: 'Spongy cottage cheese balls in light sugar syrup. (2 pcs)',
    price: 25,
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?w=400&h=300&fit=crop',
    isVeg: true,
    isAvailable: true,
    preparationTime: 3,
  },
];
